controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /index
    controller: App\Controller\DefaultController::index

about:
    path: /index/about
    controller: App\Controller\DefaultController::about

